### ISSUE TITLE
Doesn't work with .Net Blazor

### ISSUE THREAD

**Issue by nicholasyin** [use-bootstrap/use-bootstrap-tag#2]
This is probably an edge case. But when I integrate this library and use Blazor data binding, once I hit the separator character, e.g. comma, the entire <input> element is just gone. Tried without data binding it works though.

**Comment by erwinheldy** [comment]
Since I've never tried Blazor I don't know how to debug it, could you please provide a demo to reproduce the problem?

**Comment by nicholasyin** [comment]
I would if I could. It's not easy to provide a Blazor demo though. Here I'm attaching 2 screenshots in the hope of helping locate the issue.
<img width="864" alt="image" src="https://github.com/use-bootstrap/use-bootstrap-tag/assets/17007651/bd9863ec-670b-4146-861f-ac2349c8db98">
<img width="866" alt="image" src="https://github.com/use-bootstrap/use-bootstrap-tag/assets/17007651/caf12e33-e236-425b-b8b8-76f85c1d9337">
Here I've got 2 input textboxes. The upper one works fine but once I hit comma on the second one both textboxes are gone. Something I observe is that the size, height especially, changes. Maybe this is the reason why they don't show anymore.

**Comment by erwinheldy** [comment]
Please try the latest version, let me know if it works or not

**Comment by nicholasyin** [comment]
> Please try the latest version, let me know if it works or not

Glad to see that it fixes the issue! One small issue though, for the re-initialization case, is that after the new tag gets added, the input textbox lost focus automatically, while in normal cases I can keep typing and adding tags constantly.

**Comment by erwinheldy** [comment]
Reinitializing means deleting the previous element and creating a new element. As a result, the focus state will be lost automatically.

I don't understand why Blazor has to reinitialize the input.

**Comment by nicholasyin** [comment]
Well, I can't observe the Blazor reinitialization explicitly, since the resulting input element has nothing different than it is in the Blazor source code file. It's the tag library that hides the original input element and adds a couple of new ones.
Anyway, after a second thought, since the tag library hides the original input there's no point to attach Blazor's data binding attributes to it. So using it as a regular input element is fine and I need to call the `getValues` method explicitly and set it to the bound model before POSTing.
