### ISSUE TITLE
Roadmaps about bootstrap tag

### ISSUE THREAD

**Issue by FahaoTang** [use-bootstrap/use-bootstrap-tag#3]
Hi,
I am wondering if you have plans to also support some other features provided by the following project?
For example, integrating with APIs to limit the tags that can be input, etc. 

https://github.com/bootstrap-tagsinput/bootstrap-tagsinput

**Comment by erwinheldy** [comment]
Hi,
For now there is no roadmap, and yeah the "maximum limit" feature is important.
Added in version 2.1.0
